refactor: format project
TelitsynNikita/bookkeeper pull request #32
Opened 2022-08-30 12:09 UTC by Vadimochek

Прогнал проект по линтеру, вот что получилось.

2022-08-30 12:45 UTC, citrusqwe approved these changes

2022-08-31 02:23 UTC, sunn-shinne commented
Предлагаю добавить линтер в зависимости проекта, работал чтобы он у всех. И для prettier конфиг файл надо создать. Сделаешь, пожалуйста?

2022-08-31 09:08 UTC, Vadimochek commented
> Предлагаю добавить линтер в зависимости проекта, чтобы он работал у всех. Сделаешь, пожалуйста?

По идее он уже есть, файлы для него я добавил, просто надо настроить здесь:
![image](https://user-images.githubusercontent.com/56549726/187641571-8207f77d-3f93-4328-960e-ba23b5505c65.png)
1) Открыть настройки проекта
2) Выбрать категорию "Языки и фреймворки"
3) JavaScript -> Prettier
4) Выбираете путь prettier package: (Путь до проекта)\bookkeeper\client\node_modules\prettier
5) Я поставил галочку "On 'Reformat Code' action", чтобы с помощью комбинации всё форматировалось как надо

2022-09-01 04:00 UTC, sunn-shinne commented
Я про tslint, а не про prettier. У нас же есть фалы конфигурации для tslint, но его самого в зависимостях нет

2022-09-01 04:51 UTC, Vadimochek commented
> Я про tslint, а не про prettier. У нас же есть фалы конфигурации для tslint, но его самого в зависимостях нет

Как я понял, его нужно установить глобально, потому что в локальном проекте Webstorm отказывается принимать линтер и соответственно не даёт его настроить. TSLint устарел, поэтому я говорю о ESLint'e.

2022-09-01 05:03 UTC, sunn-shinne commented
> Как я понял, его нужно установить глобально, потому что в локальном проекте Webstorm отказывается принимать линтер и соответственно не даёт его настроить. TSLint устарел, поэтому я говорю о ESLint'e.

Ну вообще по идее все должно быть в зависимостях, а не глобально. Если устанавливать глобально то 100% у нас окажутся разные версии пакетов. И скорее всего, у кого то не будет установлено вообще никакой версии. А это не кул. Странно, что веб шторм как то не так себя ведет. 
А по поводу неактуальности TSLint, как скажешь. Я просто думала, что TSLint это для TS, а ESLint для JS :)

2022-09-01 05:46 UTC, Vadimochek commented
> > Как я понял, его нужно установить глобально, потому что в локальном проекте Webstorm отказывается принимать линтер и соответственно не даёт его настроить. TSLint устарел, поэтому я говорю о ESLint'e.
> 
> Ну вообще по идее все должно быть в зависимостях, а не глобально. Если устанавливать глобально то 100% у нас окажутся разные версии пакетов. И скорее всего, у кого то не будет установлено вообще никакой версии. А это не кул. Странно, что веб шторм как то не так себя ведет. А по поводу неактуальности TSLint, как скажешь. Я просто думала, что TSLint это для TS, а ESLint для JS :)

Так-то согласен, попробую разобраться, почему веб шторм не принимает локалку, надеюсь пофиксю)

2022-09-01 09:29 UTC, real3060 approved these changes

2022-09-01 09:31 UTC, real3060 requested changes
конфликты

2022-09-02 06:09 UTC, Vadimochek commented
Днём поправлю конфликты и запушу коммит с линтером

2022-09-02 15:15 UTC, merged