Feat/search bar
TelitsynNikita/bookkeeper pull request #33
Opened 2022-08-31 08:47 UTC by VanCode111

Добавлен блок поиска

2022-08-31 09:14 UTC, citrusqwe commented on client/src/app/components/table-header/actions/actions.component.html
> +      data-action="COMPLETE"
тут можно использовать константы

2022-08-31 19:12 UTC, Vadimochek approved these changes

2022-09-01 04:12 UTC, sunn-shinne approved these changes

2022-09-01 04:12 UTC, sunn-shinne commented on client/src/app/components/table-header/table-header.component.ts
> +  { value: FILTER_OPTIONS.NEW, label: "Новые" },
а как отфильтровать по параметру "Новые"? это типа те, которые еще не взяты в работу?

2022-09-01 09:12 UTC, TelitsynNikita approved these changes

2022-09-02 14:19 UTC, real3060 requested changes
поправить конфликты

2022-09-02 14:59 UTC, merged